use_frameworks!

platform :ios, '9.0'

target 'UniLoginFramework_Example' do
  pod 'UniLoginFramework', :path => '../'

  target 'UniLoginFramework_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
